### ISSUE TITLE
<a/>.toString() fails to parse

### ISSUE THREAD

**Issue by lydell** [JamesHenry/typescript-estree#66] opened 2018-12-27 10:32 UTC
**What version of TypeScript are you using?**
3.2.2

**What version of `typescript-estree` are you using?**
7.0.0

**What code were you trying to parse?**

```ts
<a/>.toString()
```

**What did you expect to happen?**
Something like this:
```
{ type: 'Program',
  range: [ 0, 17 ],
  loc:
   { start: { line: 1, column: 0 }, end: { line: 1, column: 17 } },
  body:
   [ { type: 'ExpressionStatement',
       range: [Array],
       loc: [Object],
       expression: [Object] } ],
  sourceType: 'script' }
```

**What actually happened?**
An error was thrown:
```

/home/lydell/stuff/typescript/node_modules/typescript-estree/dist/ast-converter.js:37
        throw convertError(ast.parseDiagnostics[0]);
        ^
[object Object]
```

**Repro repo:** https://github.com/lydell/typescript-estree-jsx-issue

Prettier issue: https://github.com/prettier/prettier/issues/5683

**Comment by j-f1** [comment] 2018-12-27 12:21
Looks like this is probably an issue with the original TypeScript package, as we just throw any errors TS gives us.

**Comment by armano2** [comment] 2018-12-27 13:39
@j-f1 @lydell issue is related to this line: https://github.com/JamesHenry/typescript-estree/blob/master/src/parser.ts#L134

**Comment by lydell** [comment] 2018-12-27 13:43
Thanks. I'm not very familiar with using TypeScript, so I wasn't sure how to test it in isolation.

**Comment by armano2** [comment] 2018-12-27 13:51
@lydell right now there is no way to change this option :(

**Comment by JamesHenry** [comment] 2018-12-27 14:55
Yep, confirmed that in the normal JSX configuration the TypeScript parser (via https://astexplorer.net/) will produce `parseDiagnostics` for this source. This is a tricky one... :/

**Comment by armano2** [comment] 2018-12-27 19:59
@lydell @JamesHenry i did a little more tests, and looks like this syntax is not allowed in typescript at all.
you have to do 

```ts
(<a/>).toString()
```

**Comment by JamesHenry** [comment] 2018-12-28 18:32
I don't think there is much we can do about this on this side, and it seems like we are going to address it on the Prettier side, so closing for now

**Closed by JamesHenry** 2018-12-28 18:32 UTC
